// vietnamCities.ts
export const vietnamCities = [
    { value: 'Hanoi', label: 'Hà Nội' },
    { value: 'HCMC', label: 'Thành phố Hồ Chí Minh' },
    { value: 'DaNang', label: 'Đà Nẵng' },
    { value: 'Hue', label: 'Huế' },
    { value: 'NhaTrang', label: 'Nha Trang' },
    { value: 'HaiPhong', label: 'Hải Phòng' },
    { value: 'CanTho', label: 'Cần Thơ' },
    { value: 'Vinh', label: 'Vinh' },
    { value: 'NamDinh', label: 'Nam Định' },
    { value: 'QuangNinh', label: 'Quảng Ninh' },
    { value: 'BacNinh', label: 'Bắc Ninh' },
    { value: 'BinhDuong', label: 'Bình Dương' },
    { value: 'ThaiNguyen', label: 'Thái Nguyên' },
    { value: 'LongAn', label: 'Long An' },
    { value: 'HaNam', label: 'Hà Nam' },
    { value: 'PhuTho', label: 'Phú Thọ' },
    { value: 'NinhBinh', label: 'Ninh Bình' },
    { value: 'TayNinh', label: 'Tây Ninh' },
    { value: 'LamDong', label: 'Lâm Đồng' },
    { value: 'DakLak', label: 'Đắk Lắk' },
    { value: 'KhanhHoa', label: 'Khánh Hòa' },
    { value: 'TraVinh', label: 'Trà Vinh' },
    { value: 'DakNong', label: 'Đắk Nông' },
    { value: 'SocTrang', label: 'Sóc Trăng' },
    { value: 'BinhThuan', label: 'Bình Thuận' },
    { value: 'QuangNam', label: 'Quảng Nam' },
    { value: 'QuangBinh', label: 'Quảng Bình' },
    { value: 'NgheAn', label: 'Nghệ An' },
    { value: 'GiaLai', label: 'Gia Lai' },
    { value: 'KonTum', label: 'Kon Tum' },
    { value: 'HauGiang', label: 'Hậu Giang' },
    { value: 'BenTre', label: 'Bến Tre' },
    { value: 'BacLieu', label: 'Bạc Liêu' },
    { value: 'CaMau', label: 'Cà Mau' },
    // Thêm nhiều thành phố khác nếu cần
];